# Generated by Django 4.0.4 on 2022-04-14 13:18

import os

from django.db import migrations
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
    ]

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        DJANGO_SU_USERNAME = os.environ.get('DJANGO_SU_USERNAME')
        DJANGO_SU_EMAIL = os.environ.get('DJANGO_SU_EMAIL')
        DJANGO_SU_PASSWORD = os.environ.get('DJANGO_SU_PASSWORD')

        if User.objects.filter(username=DJANGO_SU_USERNAME).exists():
            return

        superuser = User.objects.create_superuser(
            username=DJANGO_SU_USERNAME,
            email=DJANGO_SU_EMAIL,
            password=DJANGO_SU_PASSWORD,
            last_login=timezone.now())

        superuser.save()

    operations = [migrations.RunPython(generate_superuser)]
